### ISSUE TITLE
Missing stair corner interaction

### ISSUE THREAD

**Issue by Autoskip** [FirEmerald/AdditionalPlacements#42] opened 2023-10-09 21:12 UTC
![2023-10-10_08 09 23](https://github.com/FirEmerald/AdditionalPlacements/assets/5525023/1b67e0c8-4e25-4dba-bd5f-43016c5daa0d)
I think the picture speaks for itself, but I should probably mention that this was on 1.18.2 as I haven't had much success at getting modded minecraft to launch at later versions.

**Comment by FirEmerald** [comment] 2023-10-10 03:36
That's not a bug; I never coded that specific case. I'll consider it as a future addition but given how complex the blockstate logic already can be it won't be a simple job. In the meantime, there is a screenshot on the curseforge page that shows all the additional stair placement shapes.

**Comment by Autoskip** [comment] 2023-10-10 04:45
Yeah, I'd seen that - I was more thinking of it being a bug in that one logical (but somewhat obscure) interaction and its mirrors/rotations had been missed in a system that accounted for literally every other logical interaction (I checked), and wanted to make sure that it was known by the author.

I'm not going to close this issue, in the hopes that it will get added in the future, but I can understand why it might not be something that can be added on a whim.

**Comment by FirEmerald** [comment] 2023-10-11 03:27
Well I ended up doing it anyways, expect it in the next release.
marking fixed as of:
https://github.com/FirEmerald/AdditionalPlacements/commit/b5e4f7e3e19cd0ddffa2bd044162bc16b8cc540d
https://github.com/FirEmerald/AdditionalPlacements/commit/540a7669a502e4b29a5ff8cc119acf66fa3efc7d
https://github.com/FirEmerald/AdditionalPlacements/commit/bee8473372cb2a82344ce5fedf6d6a37985a17dd

**Closed by FirEmerald** 2023-10-11 03:27 UTC
